### ISSUE TITLE
Showing one single competition twice as of API error

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/treecounter-app#1450]
**Describe the bug**
I created a competition and edited it once more to change the image. Afterwards the backend API call returns the competition twice.

**Is it on a Production or Development Build?**
staging

**To Reproduce**
1. Go to 'competitions'
2. Create a new competition
3. Edit the competition
4. Load the list of own competitions

**Expected behavior**
Only list one competition and only get one competition from the API.

**What actually happens**
The own competition is displayed twice as returned twice by the API.

**Screenshots**
![Simulator Screen Shot - iPhone X - 2019-09-23 at 11 20 39](https://user-images.githubusercontent.com/1532418/65414768-a1556e00-ddf4-11e9-9668-d48d8adc5119.png)

**Smartphone (please complete the following information):**
- Device: iPhone X
 - OS: 12.4
 - Plant-for-the-Planet App Version 1.0.8

**Additional context**
Here is the response of the API call:
```json
{
  "merge": {
    "competitionPager": [
      {
        "id": 3,
        "category": "mine",
        "orderBy": "recent",
        "currentPage": 1,
        "maxPerPage": 2,
        "nbPages": 1,
        "nbResults": 2,
        "nbShowing": 2,
        "nbRemaining": 0,
        "nbNextResults": 0,
        "competitions": [
          {
            "id": 51,
            "slug": "norberts-wettbewerb",
            "name": "Norberts Wettbewerb",
            "ownerTreecounterId": 16,
            "ownerName": "Norbert Schuler",
            "ownerAvatar": "5d7a734a58fc9060989190.png",
            "access": "request",
            "endDate": "2019-12-23",
            "goal": 100,
            "score": 0,
            "image": "5d888c5c6f022005266714.jpeg",
            "competitorCount": 1,
            "topEnrollments": [
              {
                "id": 101,
                "treecounterId": 16,
                "treecounterSlug": "norbert-schuler",
                "treecounterDisplayName": "Norbert Schuler",
                "treecounterAvatar": "5d7a734a58fc9060989190.png",
                "score": 0
              }
            ]
          },
          {
            "id": 51,
            "slug": "norberts-wettbewerb",
            "name": "Norberts Wettbewerb",
            "ownerTreecounterId": 16,
            "ownerName": "Norbert Schuler",
            "ownerAvatar": "5d7a734a58fc9060989190.png",
            "access": "request",
            "endDate": "2019-12-23",
            "goal": 100,
            "score": 0,
            "image": "5d888c5c6f022005266714.jpeg",
            "competitorCount": 1,
            "topEnrollments": [
              {
                "id": 101,
                "treecounterId": 16,
                "treecounterSlug": "norbert-schuler",
                "treecounterDisplayName": "Norbert Schuler",
                "treecounterAvatar": "5d7a734a58fc9060989190.png",
                "score": 0
              }
            ]
          }
        ]
      }
    ]
  }
}
```

**Comment by jmiridis** [comment]
Inititally the owner of a competition could not be enrolled in his own competition. Later we decided that we would enroll him automatically. This caused the error that has been fixed.

**Comment by norbertschuler** [comment]
This hasn't yet merged to staging (or other dev branches), so the error still exists there.
